FORMAT: 1A
HOST: https://isac.sac.digital

# Login

Teste a API com isac.sac.digital
## Contactos Collection [/login]

###  Autentica Contacts [POST]

+ Request (application/json)
 {
      "client": "91b9650a-9f6d-4884-83f1-71cf528e7603",
      "password": "3SM4rFPguBqGhwHAotrd2vsV1AWKBy9lnfWSzuu9",
      "scopes": [
          "send",
          "contact"
      ]
  } 



+ Response 200 (application/json)