FORMAT: 1A
HOST: https://isac.sac.digital

# TESTE API


## Questions Collection [/contatos]


### Listar Contatos [GET]
Metodo para Listar Contatos

+ Request (application/json)

+ Response 200 (application/json)




### Importar Contato [POST]

Metodo para criar contato

+ Request (application/json)


+ Response 201 (application/json)

    + Headers


    + Body

Metodo para criar contato

+ Request (application/json)



+ Response 201 (application/json)

    + Headers



    + Body

